mutation CreateUser($data: CreateUserInput!) {
    createUser(data: $data) {
      id
      firstName
      lastName
      email
      mainPhone
      secondaryPhone
    }
  }

mutation Signin($data: SigninInput!) {
  signin(data: $data) {
    loginToken
  }
}

mutation Validate($data: ValidateUserInput!) {
  validateUser(data: $data) {
    loginToken
  }
}